FROM node:18.0.0-alpine as development

RUN apk update && apk add --no-cache git python3 build-base

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000
EXPOSE 5173

CMD ["npm", "run", "start:dev"]